# データベースに Postgresql を使用する。
spring.datasource.driver-class-name=org.postgresql.Driver

# ファイルにデータベースを作成する場合(<user>は自分のユーザ名)
spring.datasource.url=jdbc:postgresql://database:5432/appdb
spring.datasource.username=appdb
spring.datasource.password=appdb

# データベース初期化モードの設定。
spring.sql.init.mode=always
